import { ChangeEvent, useState } from 'react';
import { DeceasedPerson } from './deceased-person-domain';
import { ImportPreview, deceasedPersonCsvHeaders, parseDeceasedPersonCsv } from './deceased-person-import';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';

export function DeceasedPersonImportDialog({ existingCodes, onConfirm, onClose }: { existingCodes: string[]; onConfirm: (people: DeceasedPerson[]) => Promise<void>; onClose: () => void }) {
  const [preview, setPreview] = useState<ImportPreview | null>(null); const [fileError, setFileError] = useState(''); const [saving, setSaving] = useState(false);
  function chooseFile(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return;
    if (!file.name.toLowerCase().endsWith('.csv') && file.type !== 'text/csv') { setFileError('Chỉ nhận file CSV UTF-8.'); setPreview(null); return; }
    const reader = new FileReader(); reader.onload = () => { setPreview(parseDeceasedPersonCsv(String(reader.result ?? ''), existingCodes)); setFileError(''); }; reader.onerror = () => setFileError('Không thể đọc file CSV.'); reader.readAsText(file, 'UTF-8'); }
  const errors = preview?.invalidRows.length ?? 0; const valid = preview?.validRows.length ?? 0;
  async function confirm() { if (!preview || errors > 0) return; setSaving(true); setFileError(''); try { await onConfirm(preview.validRows); onClose(); } catch (cause) { setFileError(cause instanceof Error ? cause.message : 'Không thể import danh sách.'); } finally { setSaving(false); } }
  return <Dialog open onOpenChange={(open) => { if (!open && !saving) onClose(); }}><DialogContent className="import-dialog" showCloseButton={false}><DialogHeader><div><p className="eyebrow">IMPORT DANH MỤC</p><DialogTitle>Import hương linh</DialogTitle></div><Button type="button" variant="ghost" size="icon-sm" aria-label="Đóng import" disabled={saving} onClick={onClose}>×</Button></DialogHeader><p>Ngày mất nhập theo lịch âm dạng dd/mm, không ghi năm. Thêm cột tùy chọn <code>thang_nhuan</code> (true/false) để chỉ tháng nhuận. Header bắt buộc: <code>{deceasedPersonCsvHeaders.join(', ')}</code>.</p><Label className="file-input">Chọn file CSV<Input aria-label="Chọn file CSV" type="file" accept=".csv,text/csv" onChange={chooseFile} /></Label>{fileError && <p role="alert" className="notice">{fileError}</p>}{preview && <><p className="import-summary">{valid} dòng hợp lệ, {errors} dòng lỗi</p><div className="preview-table"><Table><TableHeader><TableRow><TableHead>Dòng</TableHead><TableHead>Mã số</TableHead><TableHead>Họ tên</TableHead><TableHead>Kết quả</TableHead></TableRow></TableHeader><TableBody>{preview.rows.map((row) => <TableRow key={row.rowNumber}><TableCell>{row.rowNumber}</TableCell><TableCell>{row.person?.code}</TableCell><TableCell>{row.person?.fullName}</TableCell><TableCell>{row.errors.length ? row.errors.map((error) => <p key={error} className="row-error">{error}</p>) : 'Sẵn sàng'}</TableCell></TableRow>)}</TableBody></Table></div>{errors > 0 && <p className="notice" role="alert">Hãy sửa file nguồn rồi chọn lại; không thể xác nhận khi còn lỗi.</p>}</>}<DialogFooter><Button type="button" variant="catalog" disabled={saving} onClick={onClose}>Đóng</Button><Button type="button" disabled={!preview || errors > 0 || valid === 0 || saving} onClick={() => void confirm()}>{saving ? 'Đang import…' : `Xác nhận thêm ${valid} người`}</Button></DialogFooter></DialogContent></Dialog>;
}
