import { ChangeEvent, useState } from 'react';
import { DeceasedPerson } from './deceased-person-domain';
import { ImportPreview, deceasedPersonCsvHeaders, parseDeceasedPersonCsv } from './deceased-person-import';

export function DeceasedPersonImportDialog({ existingCodes, onConfirm, onClose }: { existingCodes: string[]; onConfirm: (people: DeceasedPerson[]) => Promise<void>; onClose: () => void }) {
  const [preview, setPreview] = useState<ImportPreview | null>(null); const [fileError, setFileError] = useState(''); const [saving, setSaving] = useState(false);
  function chooseFile(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return;
    if (!file.name.toLowerCase().endsWith('.csv') && file.type !== 'text/csv') { setFileError('Chỉ nhận file CSV UTF-8.'); setPreview(null); return; }
    const reader = new FileReader(); reader.onload = () => { setPreview(parseDeceasedPersonCsv(String(reader.result ?? ''), existingCodes)); setFileError(''); }; reader.onerror = () => setFileError('Không thể đọc file CSV.'); reader.readAsText(file, 'UTF-8'); }
  const errors = preview?.invalidRows.length ?? 0; const valid = preview?.validRows.length ?? 0;
  async function confirm() { if (!preview || errors > 0) return; setSaving(true); setFileError(''); try { await onConfirm(preview.validRows); onClose(); } catch (cause) { setFileError(cause instanceof Error ? cause.message : 'Không thể import danh sách.'); } finally { setSaving(false); } }
  return <div className="dialog-backdrop"><section className="import-dialog" role="dialog" aria-modal="true" aria-labelledby="import-title"><header><div><p className="eyebrow">IMPORT DANH MỤC</p><h2 id="import-title">Xem trước danh sách người đã mất</h2></div><button type="button" aria-label="Đóng import" onClick={onClose}>×</button></header><p>File được kiểm tra trong trình duyệt trước khi gửi một lần để lưu vào danh mục. Header bắt buộc: <code>{deceasedPersonCsvHeaders.join(', ')}</code>.</p><label className="file-input">Chọn file CSV<input aria-label="Chọn file CSV" type="file" accept=".csv,text/csv" onChange={chooseFile} /></label>{fileError && <p role="alert" className="notice">{fileError}</p>}{preview && <><p className="import-summary">{valid} dòng hợp lệ, {errors} dòng lỗi</p><div className="preview-table"><table><thead><tr><th>Dòng</th><th>Mã số</th><th>Họ tên</th><th>Kết quả</th></tr></thead><tbody>{preview.rows.map((row) => <tr key={row.rowNumber}><td>{row.rowNumber}</td><td>{row.person?.code}</td><td>{row.person?.fullName}</td><td>{row.errors.length ? row.errors.map((error) => <p key={error} className="row-error">{error}</p>) : 'Sẵn sàng'}</td></tr>)}</tbody></table></div>{errors > 0 && <p className="notice" role="alert">Hãy sửa file nguồn rồi chọn lại; không thể xác nhận khi còn lỗi.</p>}</>}<footer><button type="button" className="secondary" onClick={onClose}>Đóng</button><button type="button" disabled={!preview || errors > 0 || valid === 0 || saving} onClick={() => void confirm()}>{saving ? 'Đang import…' : `Xác nhận thêm ${valid} người`}</button></footer></section></div>;
}
